#spring.data.mongodb.database=starter
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=password
#spring.data.mongodb.uri=mongodb+srv record ...
#spring.data.mongodb.port=27017

# App Properties
app:
  jwt:
    secret: mySecretKey
    expiration-in-ms: 86400000
